// <auto-generated />
using Gobi.InSync.App.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gobi.InSync.App.Migrations
{
    [DbContext(typeof(InSyncDbContext))]
    [Migration("20200613160103_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5");

            modelBuilder.Entity("Gobi.InSync.App.Persistence.Models.SyncWatch", b =>
                {
                    b.Property<string>("SourcePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("TargetPath")
                        .HasColumnType("TEXT");

                    b.HasKey("SourcePath", "TargetPath");

                    b.ToTable("Watches");
                });
#pragma warning restore 612, 618
        }
    }
}
